export { LoginPage } from './auth/login'
export { RegisterPage } from './auth/register'
export { ChatsPage } from './chats'
export { ChatPage } from './chats/chat'
export { ProfilePage } from './profile'
export { ChangeProfilePage } from './profile/change-profile'
export { ChangePasswordPage } from './profile/change-password'
