export { default as LoginPage } from './auth/login/index.ts'
export { default as RegisterPage } from './auth/register/index.ts'
export { default as ChatsPage } from './chats/index.ts'
export { default as ProfilePage } from './profile/index.ts'
export { default as ChangeProfilePage } from './profile/change-profile/index.ts'
export { default as ChangePasswordPage } from './profile/change-password/index.ts'
export { default as NotFoundPage } from './error/404/index.ts'
export { default as InternalServerErrorPage } from './error/500/index.ts'
