export { default as LoginPage } from './auth/login'
export { default as RegisterPage } from './auth/register'
export { default as ChatsPage } from './chats'
export { default as ProfilePage } from './profile'
export { default as ChangeProfilePage } from './profile/change-profile'
export { default as ChangePasswordPage } from './profile/change-password'
export { default as NotFoundPage } from './error/404'
export { default as InternalServerErrorPage } from './error/500'
